[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x555555"
blue = "0xcaa9fa"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xffffff"
yellow = "0xf1fa8c"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbbbbbb"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x282a36"
foreground = "0xf8f8f2"

[font]
size = 14

[font.bold]
family = "Fira Code"
style = "Normal"

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"


[scrolling]
history = 100000
multiplier = 3

[bell]
duration = 0

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Windowed"

[window.padding]
x = 2
y = 2

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"
